export default interface ICaptura {
    id_modulo_informacion: number | null,
    id_usuario_captura: number | null,
    select_nacionalidad?: number | null,
    select_pais_origen?: number| null,
    select_estado?: number| null,
    select_municipio?: number| null,
    select_genero?: number| null,
    diversidad_sexual?: number| null,
    edad?: number| null,
    select_escolaridad?: number| null,
    correo?: string| null,
    discapacidad?: number| null,
    numero_turista_viajando?: number| null,
    viaja_con_mascota?: number| null,
    select_proposito?: Array<number>| null,
    select_congreso?: Array<number>| null,
    select_alojamiento?: Array<number>| null,
    select_transporte?: number| null,
    select_medio?: number| null,
    select_organizador?: number| null,
    fecha_registro?: string | null,
    fecha_modificacion?: string | null
}